### PR TITLE
Link cleanup and removing a duplicate piece of advice

### PR DESCRIPTION
**Pull request by demobox**
d5214768bf9e4fe9fb52ca618c2860a124321f58 is a follow-on to #166 

/cc @nacx

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
Go to http://4839410403890131ac16-55b5764490a0342e36956fa283c469df.r55.cf5.rackcdn.com/ to review your changes.

**Comment by demobox** [comment]
Rendered:

image

Javadoc links seem to work, too.

**Comment by demobox** [comment]
@nacx I take it you're OK with this, then..? ;-)

**Comment by demobox** [comment]
@nacx Ping..?

**Comment by nacx** [comment]
lgtm :) Thanks @demobox!

**Comment by demobox** [comment]
> lgtm :)

Thanks, @nacx! Merged to [master](https://git1-us-west.apache.org/repos/asf?p=jclouds-site.git;a=commit;h=584d42566169503fd1df7d1076787abb433e3a4e)

**Pull request closed without merging**
