### PR TITLE
Support apache disclaimer

### PR DESCRIPTION
**Pull request by nacx**
/cc @demobox @andrewgaul @andreaturli

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
Go to http://987964424bc6f3db9187-b8102e22101e8a7d9c2f91ae0f2c6155.r17.cf5.rackcdn.com/ to review your changes.

**Comment by andreaturli** [comment]
thanks @nacx - is it a temporary "banner" or else? Looks a bit "invasive" IMHO

**Comment by nacx** [comment]
Yes. It is temporal during the 18 years of the ASF campaing (see the pmc emails regarding help spreading the word). Afterwards I'd leave just the link  in the footer.

**Comment by nacx** [comment]
I agree. But it is not a matter of quantity. It is about supporting the foundation we are in. Help the press and fundraising people in this campaign to spread the word about what the ASF is, its place and vision in the Open Source world, and doing so from the projects that make it a great place for OSS communities.

**Comment by demobox** [comment]
As a temporary banner, this is fine for me - it reminds me of similar banners on e.g. Wikipedia. @nacx When would be the expected take-down date?

From a styling perspective, would it make sense to break it up a bit, e.g. as follows?

image

**Comment by nacx** [comment]
I've just applied your suggestions.

>When would be the expected take-down date?

I don't really know, and it's not up to me. Whenever we find it appropriate? :)

**Comment by jclouds-commentator** [comment]
Go to http://0a7942859e28eeb58785-f455e80e1ff41e2041ab4e5cbf0e9d7c.r44.cf5.rackcdn.com/ to review your changes.

**Comment by demobox** [comment]
> I've just applied your suggestions.

image

Thanks for that! Just a minor thought: how about adding a space between the two paragraphs, as in the screenshot above?

**Comment by jclouds-commentator** [comment]
Go to http://38baa9b78c2b6a0c12e9-698068cdb509d1303795dde9b59b5cf1.r21.cf5.rackcdn.com/ to review your changes.

**Comment by nacx** [comment]
This was already merged and published.

**Pull request closed without merging**
