### PR TITLE
Align style of describing compute and blobstore improvements

### PR DESCRIPTION
**Pull request by demobox**
/cc @andrewgaul @nacx

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
Go to http://de807d73ea07fdf3360a-13309fc1a55c646f06bbf64f44b2a24c.r64.cf5.rackcdn.com/ to review your changes.

**Comment by andrewgaul** [comment]
👍

**Comment by demobox** [comment]
Merged to [master](https://git1-us-west.apache.org/repos/asf?p=jclouds-site.git;a=commit;h=68610f646f4dd7c1c58e52fc47434005d950cd00). Not published - fine if that happens whenever we make the next change (/cc @nacx).

Thanks for taking a look, Andrew G!

**Comment by nacx** [comment]
Thanks @demobox and @andrewgaul!
I've published the changes and the javadocs for 2.0.x.

**Comment by demobox** [comment]
> I've published the changes and the javadocs for 2.0.x

Great - thanks, Ignasi!

**Pull request closed without merging**
