### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by felfert**
Add missing link to 2.0.x javadoc

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
Go to http://db28c6e508cc7c000f84-4fe8c41c25aa7c42c77a072c81d57bea.r78.cf5.rackcdn.com/ to review your changes.

**Comment by felfert** [comment]
> Go to http://db28c6e508cc7c000f84-4fe8c41c25aa7c42c77a072c81d57bea.r78.cf5.rackcdn.com/ to review your changes.
That link does not work at all?! (Index shown, but nothing else)

**Comment by demobox** [comment]
> That link does not work at all?! (Index shown, but nothing else)

Odd :-( Is that still the case for you, @felfert? Staging site looks good to me:

image

Thanks for adding this!

**Comment by felfert** [comment]
Looks just like your image here (index of various javadocs shown), but if I click on **any** of those links, I get the following message:
````
Web Listing Disabled

The owner of this web site has disabled web listing.

If you are the owner of this web site, you can enable web listing by setting X-Container-Meta-Web-Listings.
Index File Not Found

The owner of this web site has set X-Container-Meta-Web-Index: index.html. However, this file is not found.
````

**Comment by nacx** [comment]
Oh, this is because javadocs are huge (and not part of the site that is rendered with jekyll) so we intentionally don't upload them to the staging site.

I'm AFK but I'll merge the PR as soon as i can. Thanks @felfert!

**Comment by nacx** [comment]
Pushed to master as [60b4308e](http://git-wip-us.apache.org/repos/asf/jclouds-site/commit/60b4308e) and published the site. Changes are now live :) Thanks @felfert!

**Comment by demobox** [comment]
> Changes are now live

Aaaand looking good:

image

image

Thanks, @felfert and @nacx!

**Pull request closed without merging**
