### PR TITLE
Encourage users to join the jclouds community

### PR DESCRIPTION
**Pull request by everett-toews**

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
Go to http://efb71e222f3e7705affa-c28abaee2e792988615b824af298484d.r45.cf5.rackcdn.com/ to review your changes.

**Comment by jclouds-commentator** [comment]
Go to http://9427ed3d3cca02c0c757-1762fad363348f9e8b76835ce645b097.r75.cf5.rackcdn.com/ to review your changes.

**Comment by jclouds-commentator** [comment]
Go to http://1ce9702f4b23293f4eec-126489b6a04fa053d60deed0afaa1eeb.r87.cf5.rackcdn.com/ to review your changes.

**Comment by everett-toews** [comment]
Merged and published.

**Pull request closed without merging**
