### PR TITLE
Added ProfitBricks logo and removed HP

### PR DESCRIPTION
**Pull request by nacx**

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
Go to http://6914889a48731d09dfce-9e25e7f19eab95e85b1d44467f959fe1.r5.cf5.rackcdn.com/ to review your changes.

**Comment by nacx** [comment]
rebuild please

**Comment by jclouds-commentator** [comment]
Go to http://85a9bb65eab7125a86d3-47099a82266197f0e5358402e177ab15.r57.cf5.rackcdn.com/ to review your changes.

**Comment by demobox** [comment]
image

Looks good to me - thanks, @nacx!

**Comment by nacx** [comment]
Pushed to master as [f1e2d75f](http://git-wip-us.apache.org/repos/asf/jclouds-site/commit/f1e2d75f). Thx @demobox!

**Pull request closed without merging**
