### PR TITLE
Remove unsupported sections (clojure, Ant, GAE)

### PR DESCRIPTION
**Pull request by neykov**
* clojure support removed from core
* reference to non-existent pages (`ApacheAntComputeGuide` & `UsingJCloudsWithGAE`)

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
Go to http://52e5085fc260ceb67e22-fa0c3b2f9d9bfd5ea649b5c10dacaba5.r41.cf5.rackcdn.com/ to review your changes.

**Comment by nacx** [comment]
Can you remove the "Usage in Google AppEngine" too?

**Comment by jclouds-commentator** [comment]
Go to http://ee3f1ff390343e30f39b-d136f4782a6445a9196f897e7072ec57.r95.cf5.rackcdn.com/ to review your changes.

**Comment by neykov** [comment]
Done @nacx

**Comment by jclouds-commentator** [comment]
Go to http://84e8de0da1a2915bcbe5-02f621e7bc2c992c40c304cd38334419.r49.cf5.rackcdn.com/ to review your changes.

**Comment by jclouds-commentator** [comment]
Go to http://71d71ba2b69c1873f826-64134700c51c773ca3459cdb14bd1042.r2.cf5.rackcdn.com/ to review your changes.

**Comment by neykov** [comment]
[Merged](https://git1-us-west.apache.org/repos/asf?p=jclouds-site.git;a=commit;h=94b98475f77b0ed6b9d9e3db2e05209b19c523f4)

**Comment by demobox** [comment]
Nice catch - thanks, @neykov!

@nacx Do you think it would make sense to add "check for references in the docs" as a TODO item for contributors and/or reviewers?

**Comment by andrewgaul** [comment]
For what it is worth, jclouds has a GAE driver although it may have bit-rotted:

https://issues.apache.org/jira/browse/JCLOUDS-836

**Comment by nacx** [comment]
@neykov mind publishing the changes to the website? You can use the `deploy-site` script.

**Comment by neykov** [comment]
Updated the site.

**Comment by nacx** [comment]
Thanks! :)

**Pull request merged**
