### PR TITLE
Updated to the new apache logo

### PR DESCRIPTION
**Pull request by nacx**

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
Go to http://fb98329d13a3bfd1186a-165d2363444fcae558f1a040cfe934c2.r66.cf5.rackcdn.com/ to review your changes.

**Comment by andrewgaul** [comment]
:+1:

**Comment by demobox** [comment]
image

Image looks good to me! Is the text "the Apache feather logo" still accurate?

Thanks for taking care of this, @nacx!

**Comment by nacx** [comment]
> Image looks good to me! Is the text "the Apache feather logo" still accurate?

Yes, I think the text is still fine.

**Comment by nacx** [comment]
Merged and published. Thanks for checking!

**Pull request merged**
