### PR TITLE
Language and minor style tweaks to Ivan's nice guest blog

### PR DESCRIPTION
**Pull request by demobox**
@nacx @ivanlomba Obviously, just a suggestion - please take a look and tweak where necessary!

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
to review your changes.

**Comment by jclouds-commentator** [comment]
to review your changes.

**Comment by nacx** [comment]
Pushed to master as [1c035552](http://git-wip-us.apache.org/repos/asf/jclouds-site/commit/1c035552). Thanks @demobox!

**Comment by demobox** [comment]
> Pushed to master as 1c035552

Thanks for taking a look so quickly, Ignasi!

**Pull request closed without merging**
