### PR TITLE
Promote ProfitBricks

### PR DESCRIPTION
**Pull request by devcsrj**

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
Go to http://8d9ffc19498b0e81bf98-41d640a19c44b3cd359364796871b5ee.r34.cf5.rackcdn.com/ to review your changes.

**Comment by nacx** [comment]
The ProfitBricks guide says you must have at least one datacenter created but this is no longer required. Mind updating that too?

**Comment by jclouds-commentator** [comment]
Go to http://3fdd1223ef8a7f24ded0-2dc92057efc79f17398d68ff78e66487.r67.cf5.rackcdn.com/ to review your changes.

**Comment by devcsrj** [comment]
Updated. Will create a PR to update README in jclouds main too

**Comment by jclouds-commentator** [comment]
Go to http://63808d1aaa6bc8b9b41f-b694a090173efe69a19bd04427e7b76e.r58.cf5.rackcdn.com/ to review your changes.

**Comment by nacx** [comment]
lgtm. Thanks!

**Comment by nacx** [comment]
Changes still need to be deployed to the jclouds.apache.org site.

**Comment by devcsrj** [comment]
Change [deployed](http://svn.apache.org/viewvc?view=revision&revision=1731869).

**Pull request merged**
