### PR TITLE
Google Cloud Storage and B2 are not in Labs anymore

### PR DESCRIPTION
**Pull request by danielkutik**

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
Go to http://960f48b0c40e2552158e-1bcefe9f75e7fcb87ed738e755e214a5.r49.cf5.rackcdn.com/ to review your changes.

**Comment by jclouds-commentator** [comment]
Go to http://5d9032ee8468038c7de8-d6a1259f6e8b2512b08510c00891bd46.r34.cf5.rackcdn.com/ to review your changes.

**Comment by danielkutik** [comment]
Done

**Comment by demobox** [comment]
Thanks for the update - looks good to me!

**Comment by gaul** [comment]
Thank you for your contribution @danielkutik!

**Comment by nacx** [comment]
Thanks, @danielkutik! Changes have been published on the website :)

**Pull request merged**
