### PR TITLE
Add JDBC user guide

### PR DESCRIPTION
**Pull request by rcoedo**

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
to review your changes.

**Comment by zack-shoylev** [comment]
+1

**Comment by jclouds-commentator** [comment]
to review your changes.

**Comment by zack-shoylev** [comment]
I fixed a configuration problem with the jenkins build.

**Comment by zack-shoylev** [comment]
Rebuild, please.

**Comment by jclouds-commentator** [comment]
to review your changes.

**Comment by jclouds-commentator** [comment]
Go to http://b39b1adb0f2b0b67e68c-ef4f94609284307858af43f4f1f95441.r81.cf5.rackcdn.com/ to review your changes.

**Comment by zack-shoylev** [comment]
merged

**Pull request closed without merging**
