### PR TITLE
Replace the ApacheCon banner with 'support the ASF'

### PR DESCRIPTION
**Pull request by demobox**
ApacheCon NA has ended

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
Go to http://bc330852f739187a4b75-2630bbd0f9c849c3279376f5ebd5604d.r53.cf5.rackcdn.com/ to review your changes.

**Comment by demobox** [comment]
Screenshot:

image

**Comment by nacx** [comment]
This looks like already merged?

>I have skepticism about any of these banners, but this improves the current page.

I'm fine with removing them. Feel free!

**Comment by nacx** [comment]
NP, I'll do :)

**Comment by demobox** [comment]
> NP, I'll do :)

Great, thanks!

**Pull request closed without merging**
