### PR TITLE
Updated link: Docuharvest has been rebranded to PDFDATA.io

### PR DESCRIPTION
**Pull request by cemerick**
(also moved to preserve alphabetization)

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
Go to http://cbfbf580e9a01ae67763-4e2021a7f034a6c18ca783a5d48d8877.r47.cf5.rackcdn.com/ to review your changes.

**Comment by andrewgaul** [comment]
Pushed to master but the deploy script generates a bunch of unexpected additions when using Ubuntu 14.04.  Any ideas what's wrong?

**Comment by nacx** [comment]
I've just tried it on OSX and it worked fine...

    At revision 1745583.
    Modified files in svn:
    M       community/users/index.html
    Are you sure you want to deploy the above changes? (y|n)

Don't really know why you get such changes, but probably something related to the dates in pages or something like that?
Do you want me to commit it? (Happy to do that) You can also enter the `site-content` folder and svn-discard all changes but the users page, then manually commit it.

**Comment by andrewgaul** [comment]
@nacx Would you mind deploying the site?  I will probably avoid doing this again until I upgrade to Ubuntu 16.04.

**Comment by nacx** [comment]
Done!

**Pull request merged**
