### PR TITLE
Blog post for Keystone V3

### PR DESCRIPTION
**Pull request by nacx**
This is a WIP for a blog post describing the new OpenStack Keystone V3 feature. Please use it as a reference if you want to test the https://github.com/jclouds/jclouds/tree/keystonev3 branch.

@andreaturli @demobox I've pushed the branch to the ASF remote (not my fork) so you can directly make changes to it to complete and amend the post.

### CODE REVIEW

**Comment by jclouds-commentator** [comment]
Go to http://70d632e19115264542a2-65bd57dc0497e14236efdb702ea2384e.r94.cf5.rackcdn.com/ to review your changes.

**Comment by jclouds-commentator** [comment]
Go to http://9b23b77c594702555ce7-939f7d41e6ba8eb6fc14c356ec3362e6.r34.cf5.rackcdn.com/ to review your changes.

**Comment by jclouds-commentator** [comment]
Go to http://0e466322a06c03cf3b55-e95f152c001cd66a2f57bdaf32c6eb5f.r27.cf5.rackcdn.com/ to review your changes.

**Comment by andreaturli** [comment]
looks very good to me, @nacx! thanks for the awesome contribution!

**Comment by jclouds-commentator** [comment]
Go to http://b90a11e3b03b328dfb58-6e5293c1b5255ad90f42abb7172c1624.r12.cf5.rackcdn.com/ to review your changes.

**Comment by jclouds-commentator** [comment]
Go to http://415fa322142a5c79f304-8864c393b92e8d5d434efc785d5ab47f.r15.cf5.rackcdn.com/ to review your changes.

**Comment by nacx** [comment]
Merged and published. Thanks @demobox!

**Comment by jclouds-commentator** [comment]
Go to http://7a9914276b9839b2b771-5654575e139a7d61fcade3aaeff69033.r23.cf5.rackcdn.com/ to review your changes.

**Pull request closed without merging**
