### PR TITLE
We still support Java 6

### PR DESCRIPTION
**Pull request by andrewgaul**

### CODE REVIEW

**Comment by andrewgaul** [comment]
Not April fools.

**Comment by jclouds-commentator** [comment]
Go to http://f490dfbf095158790589-3505549c764fe4c0b57acf62db8349a7.r3.cf5.rackcdn.com/ to review your changes.

**Comment by nacx** [comment]
>Not April fools.

LOL!

**Comment by jclouds-commentator** [comment]
Go to http://b3ed9c24aa3348558064-43c78303240b3a2590e71d5ccec9c390.r64.cf5.rackcdn.com/ to review your changes.

**Pull request closed without merging**
